touches in -u option and update it's help

diff --git a/bin/st-trans b/bin/st-trans
--- a/bin/st-trans
+++ b/bin/st-trans
@@ -19,10 +19,10 @@ change shortcut key.
 print this help and exit.
 
 -t
-Specifies the timeout in seconds at which to expire the notification.
+specifies the timeout in seconds at which to expire the translator notifications.
 
 -u
-change the urgency level.
+specifies translator notifications urgency level (low, normal, critical) in integers (0, 1, 2) respectively.
 
 -v
 invert source language with target language. note: you can't use this option when source language set to auto.
@@ -152,39 +152,32 @@ if [ -n "$1" ]; then # options
         curr_timeout=$(tail -n 1 ~/.st-trans | cut -sd ' ' -f 5)
         new_timeout=$(($2*1000))
         sed -i "s/$curr_timeout/$new_timeout/" ~/.st-trans
-	#Change urgency level:
+    # change urgency level:
     elif [ "$1" == "-u" ]; then
-		#ensure that $2 exist
-        if ! [ -n "$2" ]; then	    
+		# ensure that $2 exist
+        if ! [ -n "$2" ]; then
             help
-			exit 1
-	    fi
-	
-		#Check that input is integer
-		if ! [ "$2" -eq "$2" ] 2> /dev/null ;then
-			echo "Sorry integers only"
-			exit 1
-		fi
-
-		currentLevel=$(tail -n 1 ./.st-trans | cut -sd  \  -f 3)
-
-		case $2 in
-			0)    nextLevel='low'
-							;;
-
-			1)    nextLevel='normal'
-							;;
-
-			2)    nextLevel='critical'
-							;;
-
-			*)    echo "invalid number."
-			      help
-		          exit 1
-							;;
-			esac
-
-			sed -i "s/-u $currentLevel/-u $nextLevel/" ~/.st-trans
+            exit 1
+        fi
+		# check that $2 is integer
+        if ! [ "$2" -eq "$2" ] &> /dev/null; then
+            echo "Sorry integers only"
+            exit 1
+        fi
+        case $2 in
+            0)  new_level='low'
+                ;;
+            1)  new_level='normal'
+                ;;
+            2)  new_level='critical'
+                ;;
+            *)  echo "invalid number."
+                help
+                exit 1
+                ;;
+        esac
+        curr_level=$(tail -n 1 ~/.st-trans | cut -sd ' ' -f 3)
+        sed -i "s/$curr_level/$new_level/" ~/.st-trans
     # instant translation mode
     elif [ "$1" == "-i" ]; then
         # check if the daemon already running if not run it
