add invert languege feature.

diff --git a/bin/st-trans b/bin/st-trans
--- a/bin/st-trans
+++ b/bin/st-trans
@@ -119,27 +119,42 @@ if [ -n "$1" ]; then # options
             sed -i "s/$curr_key/$new_key/" ~/.xbindkeysrc
 	    xbindkeys
         fi
+	
+	#Reverse source languege with target languege
+	elif [ "$1" == "-v" ]; then
+        curr_source_lang_code="$(cut -sd \& -f 2 ~/.st-trans | cut -sd \= -f 2)" #only language code without "sl="
+		if [ "$curr_source_lang_code" == "auto" ]; then
+			notify-send -u critical -t 0 "Error, source language have been set to auto" "cannot replaced with target language"
+			exit 1
+		fi
 
+        curr_target_lang_code="$(cut -sd \& -f 3 ~/.st-trans | cut -sd \= -f 2)" #only language code without "tl="
+        sed -i "s/sl=$curr_source_lang_code/sl=$curr_target_lang_code/g" ~/.st-trans #replace source with target this will make source and target same
+		sed -i "s/sl=$curr_target_lang_code\&tl=$curr_target_lang_code/sl=$curr_target_lang_code\&tl=$curr_source_lang_code/g" ~/.st-trans #fix the previos issue
+
+		echo '~/.st-trans -r' >> ~/.xbindkeysrc
+		echo 'Alt + r' >> ~/.xbindkeysrc
+		
 	#Change timeout period
     elif [ "$1" == "-t" ]; then
 
-		#ensure that $2 exist
+        #ensure that $2 exist
         if ! [ -n "$2" ]; then	    
             help
-			exit 1
-	    fi
-			currentTime=$(tail -n 1 ~/.st-trans | cut -sd  \   -f 5)
-
+            exit 1
+        fi
+        
+		currentTime=$(tail -n 1 ~/.st-trans | cut -sd  \   -f 5)
 			
-			#Check that input is integer
-			if ! [ "$2" -eq "$2" ] 2> /dev/null ;then
-					    echo "Sorry integers only"
-						exit 1
-			fi
+        #Check that input is integer
+        if ! [ "$2" -eq "$2" ] 2> /dev/null ;then
+            echo "Sorry integers only"
+            exit 1
+        fi
 
-			timeout=$(($2*1000))
+        timeout=$(($2*1000))
 
-			sed -i "s/-t $currentTime/-t $timeout/" ~/.st-trans
+        sed -i "s/-t $currentTime/-t $timeout/" ~/.st-trans
 			
 			
 	#Change urgency level:
